export const fonts = [
    "Georgia",
    "serif",
    "Palatino Linotype",
    "Book Antiqua",
    "Palatino",
    "Times New Roman",
    "Times",
    "Arial",
    "Helvetica",
    "sans-serif",
    "Arial Black",
    "Gadget",
    "Comic Sans MS",
    "cursive",
    "Impact",
    "Charcoal",
    "Lucida Sans Unicode",
    "Lucida Grande",
    "Tahoma",
    "Geneva",
    "Trebuchet MS",
    "Helvetica",
    "Verdana"
];
